config/routes.rb
Rocweibo::Application.routes.draw do
  resources :messages do
    resources :replies
  end

  root :to => "messages#index"
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :replies
  
  validates_presence_of :body
  validates_length_of :body, :maximum=>140 
  
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :message
  
  validates_length_of :body, :minimum => 1, :maximum => 50
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.all
    @message  = Message.new

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message  = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to(messages_url) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
    end
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    @message = Message.find(params[:message_id])
    rep = @message.replies.create(params[:reply])
    respond_to do |format|
      format.html {
        if rep.save
          err = nil
        else
          err = "Couldn't save reply, try again."
        end
        
        redirect_to(message_path(rep.message), :notice => err)
      }
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails on Campus - Weibo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	
<div class="frame">
	<h1>Rails on Campus - Weibo</h1>
	<div class="page">
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/messages/_form.html.erb
<div class="message_form">	
<%= form_for(@message || Message.new) do |f| %>
  <% if @message && @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body, "What's going on?" %>
    <%= f.text_area :body, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit "Share!" %>
  </div>
<% end %>
</div>

app/views/messages/index.html.erb
<%= render 'form'%>

<div class="messages">
	<h3>Public Timeline:</h3>
	<ul>
	<% @messages.reverse.each do |message| %>
		<li class="message">
      	<%= link_to %{
        	<div class='message_body'>#{message.body}</div>
        	<div class="count left">#{pluralize(message.replies.size, 'reply')}</div>
        	<div class="timestamp right">#{time_ago_in_words(message.created_at)}</div>
        	<div class="clear">&nbsp;</div>
      	}.html_safe, message %>
    	</li>
	<% end %>
	</ul>
</div>

app/views/messages/show.html.erb
<div class="show">

<div class="nav">
  <%= link_to "&laquo; All Messages".html_safe, messages_path %>
</div>

<div class="message">
  Someone said:
  <div class="message_body"><%= @message.body %></div>
  <div class="destroy left">
    <%= link_to 'Delete this message', @message, :method => :delete,
      :confirm => 'There is no undo, please confirm.' %>
  </div>
  
  <div class="timestamp right"><%=time_ago_in_words(@message.created_at)%> ago</div>
  <div class="clear">&nbsp;</div>
</div>

<%= render 'replies/list', :msg => @message%>


</div>

app/views/replies/_form.html.erb
<%=form_for([msg, msg.replies.build]) do |f|%>
    <div class="field left">
      <%= f.label :body, "Add a reply:" %>
      <%= f.text_field :body, :maxlength => 40, :style=>'width:70%' %>
    </div>
    <div class="actions right" style="text-align:right">
      <%= f.submit "Reply"%>
    </div>
<% end %>

app/views/replies/_list.html.erb
<div class="replies">
  <% if flash[:notice] %>
      <div class='notice'><%=flash[:notice]%></div>
  <% end %>
  
      <strong>Replies:</strong>
      <ul>
      <% msg.replies.each do |rep| %>
        <li>
	  		<div class="comment_body left">&raquo; &nbsp;<%=rep.body %></div>
	  		<div class="timestamp right"><%=time_ago_in_words(rep.created_at)%> ago</div>
            <div class="clear">&nbsp;</div>
        </li>
      <% end %>
	
        <li class="reply_form"> 
          <%=render 'replies/form', :msg => msg %>
          <div class="clear">&nbsp;</div>
        </li>
      </ul>
        
</div>